version: "2"
#if needed to map the orthancPACS to a different hard disk device (after mounting it in path)
# volumes: ["/home/petctviewer/orthanc:/var/lib/orthanc/db:Z"]

networks:
  web:
    external: true
  internal:
    external: false

services:

    orthanctoolsjs:
        image: ghcr.io/salimkanoun/orthanc-tools-js:latest
        container_name: orthanctoolsjs
        restart: unless-stopped
        ports: ["8080:4000"]
        depends_on: [ postgres ]
        volumes: ["orthanctoolsjs:/OrthancToolsJs/data:Z"]
        environment:
            TZ: "Europe/Paris"
            ORTHANC_ADDRESS: "http://127.0.0.1/orthanc"
            ORTHANC_PORT: "80"
            ORTHANC_USERNAME: "lcw112"
            ORTHANC_PASSWORD: "test"
            DOMAIN_PROTOCOL: "http"
            DOMAIN_ADDRESS: "localhost"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            REDIS_PASSWORD: ""
            DB_USERNAME: "postgres"
            DB_PASSWORD: "postgres"
            DB_HOST: "postgres"
            DB_PORT: 5432
            DB_NAME: orthanctoolsjs
        networks:
          - internal
          - web
        labels:
        - "traefik.enable=true"
        - "traefik.port=4000"
        - "traefik.http.routers.blog.rule=Host(`0e44be91-4285-440b-a132-c6580851eed7.pub.instances.scw.cloud`)"
        - "traefik.http.routers.blog.entrypoints=websecure"
        - "traefik.docker.network=web"

    redis:
        image: redis:alpine
        networks:
          - internal


    postgres:
        container_name: postgresorthanctoolsjs
        image: postgres:13.1
        networks:
          - internal
        environment:
            POSTGRES_DB : "orthanctoolsjs"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: unless-stopped


volumes:
        orthanc:
        orthancpacs:
        orthanctoolsjs:
        postgres: